repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.10
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix, --select=I, --select=F401]
    # Run the formatter.
    - id: ruff-format
      args: [ --line-length=99 ]

