name: Package exe with PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Python Exe - Linux
        uses: sayyid5416/pyinstaller@v1.2.0
        with:
          python_ver: '3.7'
          spec: 'main.spec'
          requirements: 'requirements.txt'
      - name: Make file executable
        run: chmod +x dist/FinalBIGv2
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FinalBIGv2 - Linux
          path: dist
        
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Python Exe - Windows
        uses: sayyid5416/pyinstaller@v1.2.0
        with:
          python_ver: '3.7'
          spec: 'main.spec'
          requirements: 'requirements.txt'
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FinalBIGv2 - Windows
          path: dist